FROM maven:3.8.4-openjdk-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package
FROM openjdk:17-jdk-slim AS runtime
WORKDIR /app
COPY --from=build /app/target/hello-world-web-service-1.0-SNAPSHOT.jar ./app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
