services:
  apache:
    image: httpd:latest
    ports:
      - 5000:80
  mysql:
    image: mysql:latest
    ports:
      - 5432:80
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 5001:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password