services:
  couchbase:
    image: couchbase:latest
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
    volumes:
      - couchbase_data:/opt/couchbase/var
  volumes:
    couchbase_data: